package util

const (
	TRADE_TYPE_BUY  = "TRADE_TYPE_BUY"
	TRADE_TYPE_SELL = "SELL"
)

const (
	ORDER_STATUS_EXECUTED  = "ORDER_STATUS_EXECUTED"
	ORDER_STATUS_COMPLETED = "COMPLETED"
	ORDER_STATUS_PENDING   = "PENDING"
	ORDER_STATUS_CANCELED  = "CANCELED"
	ORDER_STATUS_FAILED    = "FAILED"
)
